
name: otus_hw8

on:
  push:
    branches: [ "main" ]
    paths:
     - 'hm8/**'
  pull_request:
    branches: [ "main" ]
    paths: 
     - 'hm8/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
    - run: sudo apt install libboost-filesystem-dev
    - run: sudo apt install libboost-program-options-dev
    - run: sudo apt install libboost-regex-dev
    - run: aptitude search boost 
    - run: cmake ${{github.workspace}}/hm8 -DCMAKE_BUILD_TYPE="Release" -DPATCH_VERSION=${{ github.run_number }} 
    - run: cmake --build .
    - run: cmake --build . --target package
    
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
      with:
        tag_name: hw8_${{ github.run_number }}
        release_number: Release  ${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload build
      uses: actions/upload-artifact@v4 
      with:
        name: homework8
        path: /home/runner/work/otus_c_plus_hw8/otus_c_plus_hw8/
